version: '3'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: client-service:1.0.0
    ports:
      - 5000:5000
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: server-service:1.0.0
    ports:
      - 5001:5001
