apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cs3219
  name: catalog-service-deployment
  labels:
    app: catalog-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: catalog-service
  template:
    metadata:
      name: catalog-service
      labels:
        app: catalog-service
    spec:
      containers:
      - name: catalog-service
        image: taska2/catalog-service:1.0.0
        ports:
        - containerPort: 8080
